# Generated by Django 5.1.6 on 2025-07-20 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_allergy_drug_allergy_conflicts'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(blank=True, max_length=255, null=True)),
                ('date_noted', models.DateField(blank=True, null=True)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_allergies', to='drugs.allergy')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_allergies', to='patients.patient')),
            ],
            options={
                'unique_together': {('patient', 'allergy')},
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='patients', through='patients.PatientAllergy', to='drugs.allergy'),
        ),
    ]
