# Generated by Django 5.1.6 on 2025-07-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientallergy',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
