# Generated by Django 5.1.6 on 2025-08-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adherence_score',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Medication adherence score (0.00-1.00)', max_digits=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='breastfeeding',
            field=models.BooleanField(default=False, help_text='Is patient breastfeeding?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='kidney_function',
            field=models.CharField(blank=True, help_text='e.g., Normal, Mild impairment, Severe impairment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_adherence_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='liver_function',
            field=models.CharField(blank=True, help_text='e.g., Normal, Mild impairment, Severe impairment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnancy_status',
            field=models.BooleanField(default=False, help_text='Is patient pregnant?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True),
        ),
    ]
