# Generated by Django 5.1.6 on 2025-08-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_adherence_score_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
