# Generated by Django 5.1.6 on 2025-10-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_doctor_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='adherence_score',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='breastfeeding',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='kidney_function',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_adherence_update',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='liver_function',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pregnancy_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='patientallergy',
            name='severity',
        ),
    ]
