# Generated by Django 5.1.6 on 2025-10-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_patient_adherence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientallergy',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
