# Generated by Django 5.1.6 on 2025-09-06 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0007_remove_doctor_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='SafePrescribe Clinic', max_length=200)),
                ('clinic_address', models.TextField(blank=True)),
                ('clinic_phone', models.CharField(blank=True, max_length=20)),
                ('clinic_email', models.EmailField(blank=True, max_length=254)),
                ('default_consultation_duration', models.IntegerField(default=30, help_text='Default consultation duration in minutes')),
                ('max_queue_size', models.IntegerField(default=50, help_text='Maximum number of patients in queue')),
                ('emergency_bump_enabled', models.BooleanField(default=True, help_text='Allow emergency patients to bump queue')),
                ('send_sms_notifications', models.BooleanField(default=False)),
                ('send_email_notifications', models.BooleanField(default=True)),
                ('notification_advance_time', models.IntegerField(default=15, help_text='Minutes before appointment to send notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Settings',
                'verbose_name_plural': 'Clinic Settings',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('normal', 'Normal Consultation'), ('emergency', 'Emergency'), ('follow_up', 'Follow-up'), ('checkup', 'Routine Checkup')], default='normal', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('estimated_duration', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('reason', models.TextField(help_text='Reason for visit/symptoms')),
                ('diagnosis', models.TextField(blank=True, help_text="Doctor's diagnosis", null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Emergency'), (2, 'High Priority'), (3, 'Normal'), (4, 'Low Priority')], default=3)),
                ('queue_position', models.IntegerField(default=0, help_text="Position in doctor's queue")),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['priority', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('estimated_wait_time', models.IntegerField(default=0, help_text='Estimated wait time in minutes')),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='clinic.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'status'], name='clinic_appo_doctor__9fdbcd_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_time'], name='clinic_appo_schedul_ff804a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['priority', 'status'], name='clinic_appo_priorit_7dde23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('doctor', 'position')},
        ),
    ]
