# Generated by Django 5.1.6 on 2025-08-10 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0005_drug_breastfeeding_safe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyPatternAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_patients_with_allergy', models.IntegerField(default=0)),
                ('percentage_of_population', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('most_common_age_group', models.CharField(blank=True, max_length=20, null=True)),
                ('gender_distribution', models.JSONField(default=dict)),
                ('common_drug_conflicts', models.JSONField(default=list)),
                ('severity_distribution', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.allergy')),
            ],
            options={
                'ordering': ['-total_patients_with_allergy'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_prescriptions', models.IntegerField(default=0)),
                ('active_prescriptions', models.IntegerField(default=0)),
                ('completed_prescriptions', models.IntegerField(default=0)),
                ('cancelled_prescriptions', models.IntegerField(default=0)),
                ('expired_prescriptions', models.IntegerField(default=0)),
                ('antibiotics_count', models.IntegerField(default=0)),
                ('analgesics_count', models.IntegerField(default=0)),
                ('antihypertensives_count', models.IntegerField(default=0)),
                ('antidiabetics_count', models.IntegerField(default=0)),
                ('statins_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
                ('allergy_warnings_count', models.IntegerField(default=0)),
                ('drug_interaction_warnings_count', models.IntegerField(default=0)),
                ('duplicate_therapy_warnings_count', models.IntegerField(default=0)),
                ('average_adherence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('low_adherence_patients_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='SafetyScoreAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average_safety_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('high_safety_prescriptions', models.IntegerField(default=0)),
                ('medium_safety_prescriptions', models.IntegerField(default=0)),
                ('low_safety_prescriptions', models.IntegerField(default=0)),
                ('contraindicated_prescriptions', models.IntegerField(default=0)),
                ('safety_by_category', models.JSONField(default=dict)),
                ('top_safety_issues', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='DrugInteractionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_prescription_count', models.IntegerField(default=0)),
                ('interaction_warnings_count', models.IntegerField(default=0)),
                ('severity_distribution', models.JSONField(default=dict)),
                ('affected_patients_count', models.IntegerField(default=0)),
                ('average_patient_age', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dose_adjustments_count', models.IntegerField(default=0)),
                ('therapy_changes_count', models.IntegerField(default=0)),
                ('adverse_events_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('drug1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_analytics_as_drug1', to='drugs.drug')),
                ('drug2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_analytics_as_drug2', to='drugs.drug')),
            ],
            options={
                'ordering': ['-co_prescription_count'],
                'unique_together': {('drug1', 'drug2')},
            },
        ),
        migrations.CreateModel(
            name='UsageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prescriptions_count', models.IntegerField(default=0)),
                ('total_quantity_prescribed', models.IntegerField(default=0)),
                ('average_dosage', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('average_duration_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pediatric_usage', models.IntegerField(default=0)),
                ('adult_usage', models.IntegerField(default=0)),
                ('geriatric_usage', models.IntegerField(default=0)),
                ('allergy_conflicts_count', models.IntegerField(default=0)),
                ('interaction_warnings_count', models.IntegerField(default=0)),
                ('average_safety_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_adherence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
            ],
            options={
                'ordering': ['-date', '-prescriptions_count'],
                'unique_together': {('date', 'drug')},
            },
        ),
    ]
