# Generated by Django 5.1.6 on 2025-07-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='allergy_conflicts',
            field=models.ManyToManyField(blank=True, related_name='conflicting_drugs', to='drugs.allergy'),
        ),
    ]
