# Generated by Django 5.1.6 on 2025-07-24 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_allergy_drug_allergy_conflicts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('contraindicated', 'Contraindicated')], max_length=20)),
                ('description', models.TextField()),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug1', to='drugs.drug')),
                ('drug2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug2', to='drugs.drug')),
            ],
            options={
                'ordering': ['-severity', 'drug1', 'drug2'],
                'unique_together': {('drug1', 'drug2')},
            },
        ),
    ]
