# Generated by Django 5.1.6 on 2025-07-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_druginteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='therapeutic_class',
            field=models.CharField(blank=True, help_text='Therapeutic class for duplicate therapy check (e.g., Statin, NSAID)', max_length=100, null=True),
        ),
    ]
