# Generated by Django 5.1.6 on 2025-08-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_drug_therapeutic_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='breastfeeding_safe',
            field=models.BooleanField(default=True, help_text='Safe for breastfeeding mothers'),
        ),
        migrations.AddField(
            model_name='drug',
            name='geriatric_dose_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Dose multiplier for elderly patients', max_digits=3),
        ),
        migrations.AddField(
            model_name='drug',
            name='kidney_impairment_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Dose multiplier for kidney impairment', max_digits=3),
        ),
        migrations.AddField(
            model_name='drug',
            name='liver_impairment_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Dose multiplier for liver impairment', max_digits=3),
        ),
        migrations.AddField(
            model_name='drug',
            name='max_dose_mg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum dose in mg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='min_dose_mg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum dose in mg', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='pediatric_dose_mg_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pediatric dose in mg/kg', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='pregnancy_category',
            field=models.CharField(blank=True, help_text='Pregnancy safety category (A, B, C, D, X)', max_length=1, null=True),
        ),
    ]
