# Generated by Django 5.1.6 on 2025-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_drug_breastfeeding_safe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='geriatric_dose_multiplier',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='kidney_impairment_multiplier',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='liver_impairment_multiplier',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='max_dose_mg',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='min_dose_mg',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='pediatric_dose_mg_kg',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='pregnancy_category',
        ),
        migrations.AddField(
            model_name='drug',
            name='geriatric_safe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='pediatric_safe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='pregnancy_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drug',
            name='breastfeeding_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drug',
            name='therapeutic_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DrugInteraction',
        ),
    ]
