# Generated by Django 5.1.6 on 2025-10-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_remove_drug_geriatric_dose_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Clinical name of the interaction, e.g., 'Serotonin Syndrome Risk'", max_length=255)),
                ('description', models.TextField(help_text='Detailed explanation of the interaction, its risks, and management.')),
                ('severity', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drugs', models.ManyToManyField(help_text='The set of drugs that cause this interaction when taken together.', related_name='interaction_sets', to='drugs.drug')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
