# Generated by Django 5.1.6 on 2025-07-21 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_allergy_drug_allergy_conflicts'),
        ('rx', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='refills',
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('refills', models.PositiveIntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_medications', to='rx.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='medications',
            field=models.ManyToManyField(related_name='prescriptions_in', through='rx.PrescriptionMedication', to='drugs.drug'),
        ),
    ]
