# Generated by Django 5.1.6 on 2025-07-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0003_remove_prescription_dosage_remove_prescription_drug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for prescribing this medication', null=True),
        ),
    ]
