# Generated by Django 5.1.6 on 2025-07-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0004_prescription_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedication',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason this medication was prescribed', max_length=255, null=True),
        ),
    ]
