# Generated by Django 5.1.6 on 2025-10-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0006_patientmedicationhistory_medicationadherence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmedicationhistory',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='patientmedicationhistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientmedicationhistory',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='prescriptionmedication',
            name='reason',
        ),
        migrations.DeleteModel(
            name='MedicationAdherence',
        ),
        migrations.DeleteModel(
            name='PatientMedicationHistory',
        ),
    ]
