# Generated by Django 5.1.6 on 2025-10-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx', '0007_remove_patientmedicationhistory_drug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for the prescription', null=True),
        ),
    ]
