# Generated by Django 5.1.6 on 2025-10-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('pharmacist', 'Pharmacist'), ('nurse', 'Nurse'), ('admin', 'Administrator')], default='doctor', max_length=20),
        ),
    ]
